name: pattern_set_state
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # design
  cupertino_icons: ^1.0.2

  # network
  http: ^0.13.5
  flutter_slidable: ^2.0.0
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7



flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

